---
title: Nathan DeVore - Personal Computer Science Portfolio
date: last-modified
author: Nathan DeVore
format:
    html:
        theme: Sandstone
        toc: true
        embed-resources: true
---
This web page's URL: <https://devoreni.github.io/portfolio/>


# Bio
I am a Computer Science major at Virginia Commonwealth University (VCU) with a concentration in Software Engineering and minors in Mathematics and Physics (graduating May 2025). My passion for learning new and challenging concepts has driven me to develop talents across various fields. Ultimately, I chose to specialize in Computer Science because it allows me to combine creativity with problem-solving while engaging with a dynamic and ever-evolving discipline.<br><br>
While abstraction is fundamental to Computer Science, I am driven to understand not just how tools work but also why they work the way they do. This curiosity led me to pursue minors in Mathematics and Physics. My coursework in Linear Algebra, Multivariable Calculus, and Statistics has given me a strong foundation in the mathematical principles underpinning modern machine learning techniques. Meanwhile, my studies in Modern Physics have deepened my understanding of solid-state physics which powers today’s software.<br><br>
This holistic approach to education has equipped me with a diverse and versatile skill set. I pride myself on programming quickly, efficiently, and cleanly, and I thrive on understanding technologies at a fundamental level. This enables me to adapt seamlessly to the constantly evolving landscape of the Computer Science field while contributing innovative and effective solutions.<br>

# Resume


# Projects

<https://devoreni.github.io/portfolio/StarforceInfo>