---
title: Shark Tooth Object Detection
date: last-modified
author: Nathan DeVore
format:
    html:
        theme: Sandstone
        toc: true
        embed-resources: true
---

Back to Portfolio: <https://devoreni.github.io/portfolio/><br>
GitHub Project Link: <https://github.com/devoreni/SharkTeethFinder>

# Abstract

The goal of this project was to build an end-to-end computer vision pipeline for detecting camouflaged, small, and partially obsured shark teeth. A high quality custom dataset was collected, an AWS Rekognition Custom Labels model was iteratively trained and improved, and a Flask + Render + PostgreSQL (or SQLite) website was created to serve as the front end. Extreme care was taken to ensure secret keys, access keys, and user information were never comprimised using environment variables, encryption, and modern authentication schemes. The model was measured to have an F1 score of 0.884, precision of 0.934, and recall of 0.840.

## Introduction

## Problem Statement

# Project Requirements

## Cross Platform Access

## Real World Performance

## Security

## Users

## Availability

# Solution

## Object Detection

### Data Collection

### AWS Rekognition Custom Labels

## Hosting

### Render

### PostgreSQL

# Results

## Statistics

## Demo

## Cost Analysis

## Tools Used

# Future Work

## Roboflow

## Self Training

## Domain Randomization

